### ISSUE TITLE
Library API

### ISSUE THREAD

**Issue by arturmuller** [mheiber/redux-machine#2]
Hey there. Really like what you're doing with this library. 👍 

In case you're interested in some _first-time-reader-of-readme_ feedback: I was quite surprised that a transition is indicated using a key on a returned object. To me, the expectation would be that `become` is a function — the word itself is an instruction.

A hypothetical API could look as follows:

``` js
// Taken from your example in README

const initReducer = (state = {error: null, users: []}, action) => {

    switch (action.type) {
    case 'FETCH_USERS':
        return become('IN_PROGRESS', Object.assign({}, state, {error: null}))
    default:
        return state
    }
}
```

I guess under the hood, this `become` function would still return an object with some special symbol key so that transitions to new state can be easily identified, but a function like this would basically make this an implementation detail that the end-user of your library doesn't have to worry about.

I haven't actually tried this live, so apologies if I am missing something really obvious!

**Comment by mheiber** [comment]
@arturmuller good feedback— your suggested API is how redux-loop enhances reducers, and is definitely more normal than the Symbol stuff in the current redux-machine API.

I think we can make it even simpler—what do you think of changing the API so that it's just:
`return Object.assign({}, state, {'status': 'IN_PROGRESS'}}`?

The simplified API is implemented in the [`simplify-api` branch](https://github.com/mheiber/redux-machine/tree/simplify-api).

**Comment by arturmuller** [comment]
Hey. Glad that you found the feedback useful!

I guess my point was not so much about simplicity as it was about clarity.

If I imagine I've never seen the library I might not even realize that something special is happening if the lib relies on the `status` field (I have to have knowledge of the API of this lib to know it is special). Using the symbol key is a bit better, but, yeah, a bit unusual.

I guess I was suggesting using a function because, I think, it more explicitly expresses intent; Because I am returning the output of some _special_ function, I immediately know that something _special_ is happening.

Even thought the status will eventually be merged into the state, I think that supplying it as a separate argument makes it clearer there there is more to it than just being another part of the state.

**Comment by mheiber** [comment]
Hi @arturmuller I thought hard about your feedback and experimented with different APIs. I decided to go with the special 'STATUS' key. Reasons:
- an explicit 'STATUS' key keeps the behavior closer to what one would do if not using a lib for state machines at all: https://github.com/mheiber/redux-machine/tree/simplify-api#making-finite-state-machine-reducers-without-a-library. I'd like to be up-front about how this library doesn't do much.
- Ideally, both APIs should be available to the programmer (the function one and the 'STATUS' key one). Since the former is easily defined using the latter, the latter is more flexible. So you can get the function API by making this helper: `const become = (state, status) => ({...state, {'STATUS': status})`

**Comment by arturmuller** [comment]
Yep, that is a very cool solution and makes perfect sense to me!
